# Configuration file for Travis-CI
##################################

language:
  - python
  - cpp
  - bash

python:
    - "3.7"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
         packages:
            - libgomp1
            - gcc-9
            - g++-9

jobs:
  include:
    # - os: osx
    #   python: 3.7
    #   env: CC=gcc-6 CXX=g++-6
    # - os: linux
    #   python: 3.7
    #   env: CC=clang CXX=clang
    - os: linux
      python: 3.7
      env: CC=gcc-9 CXX=g++-9

before_install:
  #  - |
  #    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #        brew update
  #        # seems to be needed on Travis due to conflicts with gcc otherwise
  #        # see https://github.com/travis-ci/travis-ci/issues/8826
  #        brew cask uninstall oclint
  #        brew install ccache
  #        export PATH="/usr/local/opt/ccache/libexec:$PATH"
  #        # needed for OPENMP support on Travis
  #        # see https://github.com/travis-ci/travis-ci/issues/8613N
  #        export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  #    fi
  - PYTHON_EXECUTABLE=$(which python)
  - BUILD_FLAGS="-DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_EXECUTABLE -DOMP_PARALLEL=ON"
  - bash dependencies/get_cmake.sh
  # - bash dependencies/get_conda.sh
  # - export PATH=`pwd`/dependencies/miniconda3/bin:$PATH
  # - source activate magritte
  - CMAKE_CMD="`pwd`/dependencies/cmake/bin/cmake"

install:
  - mkdir build; cd build;
  - $CC  --version
  - $CXX --version
  - $CMAKE_CMD $BUILD_FLAGS ..
  - make -j4
  - cd -
  - python setup.py install

script:
  - bash tests/run_all_tests.sh
