name: TestRetrySyntax
on:
  push:
    branches: [ 74-automated-builds-failing-on-http-errors ]
jobs:
  RetryTest:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y gmsh libegl1
      # retrying checkout: 3 tries, with 5 seconds wait inbetween
      - name: Check out repository code (try 1)
        id: checkouttry1
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: wait 5 s if attempt failed
        if: steps.checkouttry1.outcome == 'failure'
        run: sleep 5
      - name: Check out repository code (try 2)
        id: checkouttry2
        if: steps.checkouttry1.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: wait 5 s if attempt failed
        if: steps.checkouttry2.outcome == 'failure'
        run: sleep 5
      - name: Check out repository code (try 3)
        id: checkouttry3
        if: steps.checkouttry2.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          submodules: true
      # end retrying checkout

      # - name: Check out repository code (with retries)
      #   uses: Wandalen/wretry.action@v1.0.20
      #   with:
      #     action: actions/checkout@v3
      #     with: | #wretry does not seem to support ${{default}} at time of writing
      #       submodules: true
      #       repository: ${{github.repository}}
      #       token: ${{github.token}}
      #     attempt_limit: 3
      #     attempt_delay: 5000 #in ms

      - name: setup python
        uses: actions/setup-python@v3
      # retrying setting up conda: 3 tries, with 5 seconds wait inbetween
      - name: Install conda packages (try 1)
        id: setupcondatry1
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: magritte
          environment-file: dependencies/conda_env.yml
          auto-activate-base: false
          mamba-version: "*"
          channels: conda-forge, defaults
      - name: wait 5 s if attempt failed
        if: steps.setupcondatry1.outcome == 'failure'
        run: sleep 5
      - name: Install conda packages (try 2)
        id: setupcondatry2
        if: steps.setupcondatry1.outcome == 'failure'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: magritte
          environment-file: dependencies/conda_env.yml
          auto-activate-base: false
          mamba-version: "*"
          channels: conda-forge, defaults
      - name: wait 5 s if attempt failed
        if: steps.setupcondatry2.outcome == 'failure'
        run: sleep 5
      - name: Install conda packages (try 3)
        id: setupcondatry3
        if: steps.setupcondatry2.outcome == 'failure'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: magritte
          environment-file: dependencies/conda_env.yml
          auto-activate-base: false
          mamba-version: "*"
          channels: conda-forge, defaults
      # end retrying conda


      # - name: Install conda packages (with retries)
      #   uses: Wandalen/wretry.action@v1.0.20
      #   with:
      #     action: conda-incubator/setup-miniconda@v2 #wretry does seem to not allow setting default values inside; so we manually need to activate the conda env
      #     with: |
      #       activate-environment: magritte
      #       environment-file: dependencies/conda_env.yml
      #       auto-activate-base: false
      #       mamba-version: "*"
      #       channels: conda-forge, defaults
      #     attempt_limit: 3
      #     attempt_delay: 5000 #in ms
      # - run: conda init bash
      # - run: conda activate magritte
      - run: echo $(conda info) #debug output
      - name: build Magritte
        run: bash build.sh
        env:
          CC : gcc
          CXX: g++
