name: TestRetrySyntax
on:
  push:
    branches: [ 74-automated-builds-failing-on-http-errors ]
jobs:
  RetryTest:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repository code (without retries)
      #   uses: actions/checkout@v3
      #   with:
      #     submodules: true
      - name: Install dependencies
        run: sudo apt-get install -y gmsh libegl1
      - name: Check out repository code (with retries)
        uses: Wandalen/wretry.action@v1.0.20
        with:
          action: actions/checkout@v3
          with: | #wretry does not seem to support ${{default}} at time of writing
            submodules: true
            repository: ${{github.repository}}
            token: ${{github.token}}
          attempt_limit: 3
          attempt_delay: 5000 #in ms
      - name: setup python
        uses: actions/setup-python@v3
      - name: Install conda packages (with retries)
        uses: Wandalen/wretry.action@v1.0.20
        with:
          action: conda-incubator/setup-miniconda@v2
          with: |
            activate-environment: magritte
            environment-file: dependencies/conda_env.yml
            auto-activate-base: false
            mamba-version: "*"
            channels: conda-forge, defaults
          attempt_limit: 3
          attempt_delay: 5000 #in ms
      - name: build Magritte
        run: bash build.sh
        env:
          CC : gcc
          CXX: g++
