#todo: place after build-and-test
#note: regex taken from semver.org
name: Update version
on:
  push:
jobs:
  UpdateVersion:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Update version (locally) using commit message to determine version increase
        run: echo "NewVersion=$(python UpdateVersion.py ${{github.event.head_commit.message}})" >> $GITHUB_ENV
        working-directory: CI
      - name: Auto commit the version change
        uses: test-room-7/action-update-file@v1
        with:
          file-path: CMakeLists.txt
          commit-msg: "CI: increment version number to ${{env.NewVersion}}"
          github-token: ${{ secrets.GITHUB_TOKEN}}
          branch: version-numbers
